name: build

on: [push, pull_request]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Up OpenGL
      uses: openrndr/setup-opengl@v1
    - name: Configure CMake
      run: mkdir build && cd build && cmake ..
    - name: Build project
      run: cmake --build build --target chip8_emu
    - name: Run tests
      run: cmake --build build --target tests

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure CMake
        run: mkdir build && cd build && cmake ..
      - name: Build project
        run: cmake --build build --target chip8_emu
      - name: Run tests
        run: cmake --build build --target tests
